### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [browsefile/backend#2]
- [x]  fix download zip on https

- [ ] add unpack possibility in context menu

- [x] automate /static replacement after build at frontend

- [ ] replace http with fasthttp

- [ ] create cross platform desktop client include WEBDAV

- [ ] create cross mobile client include WEBDAV

- [ ] write preview queue to the file, to prevent swapping, and granular pop it https://stackoverflow.com/questions/30940190/remove-first-line-from-text-file-in-golang https://stackoverflow.com/questions/7151261/append-to-a-file-in-go

**Comment by stokito** [comment]
> replace http with fasthttp

The fasthttp has a focus on small request/responses for a typical JSON/REST API. You probably don't need it.
